apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-mundo-deployment
  namespace: hola-mundo-namespace  # Asegúrate de que coincida con el namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola-mundo
  template:
    metadata:
      labels:
        app: hola-mundo
    spec:
      containers:
      - name: hola-mundo
        image: jordin13/hola-mundo:latest
        ports:
        - containerPort: 80
