apiVersion: v1
kind: Service
metadata:
  name: hola-mundo-service
  namespace: hola-mundo-namespace  # Asegúrate de que coincida con el namespace
spec:
  selector:
    app: hola-mundo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30630  # Este es el puerto que usaremos para acceder al servicio
  type: NodePort  # Cambié LoadBalancer a NodePort
